#information for application name and launcher
Application:

  name: Python-VA
  asciibanner: tools/deploy-scripts/assets/asciibanner-VA.txt
  icon: tools/deploy-scripts/assets/virtualactuary.ico
  installdir: '%userprofile%\Python-VA'

  #After installation
  pause: 1

  # map "from/path/" -> "to/path"
  programdata:
    - [ ./bin, ./bin]
    - [ ./src, ./src]
    - [./Add xlwings to Excel.exe,       ./Add xlwings to Excel.exe]
    - [./Create new xlwings project.exe, ./Create new xlwings project.exe]
    - [./Python VA cmd.exe,              ./Python VA cmd.exe]
    - [./python.exe,                     ./python.exe]
    - [./Remove xlwings from Excel.exe,  ./Remove xlwings from Excel.exe]
    - [./Spyder VA.exe,                  ./Spyder VA.exe]

  startmenu:
    -'Add xlwings to Excel.exe'
    -'Create new xlwings project.exe'
    -'Python VA cmd.exe'
    -'python.exe'
    -'Remove xlwings from Excel.exe'
    -'Spyder VA.exe'

#Download Python/R (optional) and their dependencies to be deployed
Dependencies:
  deploy-scripts: 564bdb6
  python:
    - numpy==1.19.3
    - locate==0.0.1
    - openpyxl~=3.0
    - pandas~=1.1
    - xlwings
    - spyder
