#information for application name and launcher
Application:

  name: Python-VA
  asciibanner: tools/deploy-scripts/assets/asciibanner-VA.txt
  icon: tools/deploy-scripts/assets/VA.ico
  installdir: '%userprofile%\Python-VA'

  #After installation
  pause: 1

  # map "from/path/" -> "to/path"
  programdata:
    - [ ./bin, ./bin]

#  startmenu:
#    - 'src\New Sanlam Grouping Template.exe'

#Download Python/R (optional) and their dependencies to be deployed
Dependencies:
  deploy-scripts: 564bdb6
  python:
    - numpy==1.19.3
    - locate==0.0.1
    - openpyxl~=3.0
    - pandas~=1.1
    - xlwings
    - spyder
